version: "3.9"

services:
  db:
    container_name: iot_db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - iot_db_data:/var/lib/postgresql/data
    networks:
      - default

  app:
    container_name: iot_app
    restart: always
    build: .
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@iot_db:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_EXPIRES_IN_HOURS: ${JWT_ACCESS_EXPIRES_IN_HOURS}
      JWT_REFRESH_EXPIRES_IN_DAYS: ${JWT_REFRESH_EXPIRES_IN_DAYS}
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
      - iot_logs:/app/logs
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true

volumes:
  iot_db_data:
    external: true
  iot_logs:
    external: true
  uploads:
    external: true
