version: "3.9"

services:
  db:
    container_name: fastapi_db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: fastapi_app
    restart: always
    build: .
    ports:
      - "80:8000"
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRES_IN_HOURS: ${JWT_EXPIRES_IN_HOURS}
    depends_on:
      - db

    nginx:
      container_name: fastapi_nginx
      image: nginx:latest
      restart: always
      expose:
        - "8000"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app

volumes:
  db_data:
