"""empty message

Revision ID: f26fb2fbd3e9
Revises: 1b07601465f9
Create Date: 2025-08-02 03:14:20.246295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "f26fb2fbd3e9"
down_revision: Union[str, Sequence[str], None] = "1b07601465f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    userrole_enum = ENUM("ADMIN", "MANAGER", "MEMBER", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # 1단계: nullable=True로 추가 + 기본값 지정
    op.add_column(
        "users",
        sa.Column("role", userrole_enum, nullable=True, server_default="MEMBER"),
    )

    # 2단계: NOT NULL 제약 조건 추가
    op.alter_column("users", "role", nullable=False)

    # 3단계: 기본값 제거 (선택 사항)
    op.alter_column("users", "role", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
